used react-pdf-viewer to display pdf
jaymercado/balboa-digital-lms pull request #16
Opened 2024-11-23 06:05 UTC by ajoxales

2024-11-23 06:09 UTC, ajoxales commented
https://www.loom.com/share/58b4762bbc9f465f8124dd70010d8687

2024-11-23 06:40 UTC, jaymercado reviewed
ADD LOOM RECORDING OR SCREENSHOT!

2024-11-23 08:09 UTC, ajoxales commented
[https://www.loom.com/share/58b4762bbc9f465f8124dd70010d8687?sid=b57b5b5a-a780-47ca-9689-1fcedc0e8ab8](url)

2024-11-23 08:11 UTC, ajoxales commented
`<div style="position: relative; padding-bottom: 56.25%; height: 0;"><iframe src="https://www.loom.com/embed/58b4762bbc9f465f8124dd70010d8687?sid=85e0c92e-479a-4bf0-a7e4-d4bd9386c812" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;"></iframe></div>`

2024-11-23 08:13 UTC, ajoxales commented
okk

2024-11-24 10:44 UTC, jaymercado requested changes

2024-11-24 10:44 UTC, jaymercado commented on src/components/PDFRenderer.tsx
>      <div>
Do you still need this div?

2024-11-24 10:44 UTC, jaymercado commented on package.json
Uninstall previously used package to display pdf files.

2024-11-25 02:05 UTC, merged